# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pURJQPSp9PKrAohBffOaOoVvBca0ef8s
"""

from fastapi import FastAPI
app=FastAPI()

faqs={'Course':'BCA,Bcom,BBA,Data Science,Data Analytics',
      'Fees':'Fee ranges from 5000-15000',
      'Admissions':'Starts from July 1st',
      'Class_hours':'2 hours a day',
      'Duration':'Ranges from 5 months-18 months'}

@app.get('/')
def title():
  return('STUDENT ADMISSION CHATBOT')


@app.get('/chat')
def quest(question:str):
  if 'exit' in question.lower():
    return 'Thank You Vist Again'
  elif 'course' in question.lower() or 'program' in question.lower():
    return faqs['Course']
  elif 'fee' in question.lower() or 'fees' in question.lower():
    return faqs['Fees']
  elif 'admissions' in question.lower():
    return faqs['Class_hours']
  elif 'duration' in question.lower():
    return faqs['Duration']
  else:
    return 'Cannot understand your question'

